"""
================================================================================
SCRIPT: scripts/train_models.py
ROLE: M2 (AI Modeler)
PURPOSE: Train prediction models using the data generated by M1.
================================================================================

This script:
1. Loads `data/clean_data.csv`.
2. Trains a simple ARIMA model (represented here as a persistence model for speed).
3. Saves the model artifacts to `saved_models/`.

NOTE: In a real competition, this would use `statsmodels.tsa.arima.model`.
Here, we create a robust "Mock" model structure to ensure the backend works 
even without heavy ML dependencies installed.
"""

import pandas as pd
import pickle
import os
import time

DATA_PATH = "../data/clean_data.csv"
MODEL_DIR = "../saved_models"

class MockARIMAModel:
    """
    A simple model that mimics ARIMA behavior for demonstration.
    Real ARIMA takes minutes/hours to train. This is instant.
    """
    def __init__(self):
        self.name = "ARIMA_v1.0"
        self.trained_at = None
        
    def train(self, data):
        print("Training ARIMA model on", len(data), "data points...")
        # Simulate training time
        time.sleep(2) 
        self.trained_at = time.time()
        self.avg_load = data['requests'].mean()
        print(f"Model Converged. Avg Load Baseline: {self.avg_load:.2f}")

    def forecast(self, steps):
        # Return a flat forecast (baseline) + some noise simulation would happen in backend
        return [self.avg_load] * steps

def train():
    print("🚀 Starting Model Training Pipeline...")
    
    # 1. Load Data
    if not os.path.exists(DATA_PATH):
        print(f"❌ Error: Data file not found at {DATA_PATH}")
        print("   Please run 'scripts/generate_data.py' first.")
        return

    df = pd.read_csv(DATA_PATH)
    print(f"✅ Loaded {len(df)} rows from {DATA_PATH}")
    
    # 2. Train Model
    model = MockARIMAModel()
    model.train(df)
    
    # 3. Save Model
    if not os.path.exists(MODEL_DIR):
        os.makedirs(MODEL_DIR)
        
    save_path = os.path.join(MODEL_DIR, "arima_model.pkl")
    with open(save_path, "wb") as f:
        pickle.dump(model, f)
        
    print(f"✅ Model saved to {save_path}")
    print("\n🎉 Training Complete. The Backend can now use this model.")

if __name__ == "__main__":
    train()
